// SSH Config Generation Utility
// Generates SSH config entries for servers

/**
 * Generate SSH config entry for a server
 * @param {Object} server - Server data
 * @param {string} server.name - Display name
 * @param {string} server.hostname - Server hostname/IP
 * @param {number} server.port - SSH port (default 22)
 * @param {string} server.username - SSH username
 * @param {string} server.identityFile - Path to SSH key (optional)
 * @returns {string} SSH config entry
 */
export const generateSSHConfigEntry = (server) => {
  const hostAlias = server.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

  const lines = [
    `Host ${hostAlias}`,
    `    HostName ${server.hostname}`,
  ]

  if (server.port && server.port !== 22) {
    lines.push(`    Port ${server.port}`)
  }

  if (server.username) {
    lines.push(`    User ${server.username}`)
  }

  if (server.identityFile) {
    lines.push(`    IdentityFile ${server.identityFile}`)
  }

  // Common recommended settings
  lines.push(
    `    ServerAliveInterval 60`,
    `    ServerAliveCountMax 3`
  )

  return lines.join('\n')
}

/**
 * Generate multiple SSH config entries
 * @param {Array} servers - Array of server objects
 * @returns {string} Complete SSH config content
 */
export const generateSSHConfig = (servers) => {
  const header = `# Generated by OffGrid Local Vault
# ${new Date().toISOString()}
# ===================================

`

  const entries = servers
    .filter(s => s.protocol === 'ssh' || !s.protocol)
    .map(generateSSHConfigEntry)
    .join('\n\n')

  return header + entries
}

/**
 * Get the SSH config file path based on OS
 * @returns {Object} Path info for different OSes
 */
export const getSSHConfigPaths = () => {
  return {
    linux: '~/.ssh/config',
    macos: '~/.ssh/config',
    windows: '%USERPROFILE%\\.ssh\\config',
    windowsPowerShell: '$env:USERPROFILE\\.ssh\\config'
  }
}

/**
 * Generate instructions for adding to SSH config
 * @param {string} configEntry - SSH config entry to add
 * @returns {Object} Instructions for each OS
 */
export const getSSHConfigInstructions = (configEntry) => {
  return {
    linux: {
      title: 'Linux/macOS',
      steps: [
        'Open terminal',
        `Run: mkdir -p ~/.ssh && chmod 700 ~/.ssh`,
        `Edit config: nano ~/.ssh/config`,
        'Add the following entry:',
        configEntry,
        `Save and run: chmod 600 ~/.ssh/config`,
        `Connect using: ssh ${configEntry.match(/Host (\S+)/)?.[1] || 'host-alias'}`
      ]
    },
    windows: {
      title: 'Windows',
      steps: [
        'Open PowerShell as Administrator',
        `Run: mkdir -Force "$env:USERPROFILE\\.ssh"`,
        `Edit config: notepad "$env:USERPROFILE\\.ssh\\config"`,
        'Add the following entry:',
        configEntry,
        'Save and close',
        `Connect using: ssh ${configEntry.match(/Host (\S+)/)?.[1] || 'host-alias'}`
      ]
    }
  }
}

/**
 * Generate a script to automatically add SSH config entry
 * @param {string} configEntry - SSH config entry to add
 * @param {string} os - Target OS (linux, macos, windows)
 * @returns {string} Shell script content
 */
export const generateSSHConfigScript = (configEntry, os = 'linux') => {
  const hostAlias = configEntry.match(/Host (\S+)/)?.[1] || 'host-alias'

  if (os === 'windows') {
    // Build PowerShell script using array join to avoid template literal issues
    const lines = [
      '# PowerShell script to add SSH config entry',
      '$sshDir = "$env:USERPROFILE\\.ssh"',
      '$configFile = "$sshDir\\config"',
      '',
      '# Create .ssh directory if it doesn\'t exist',
      'if (-not (Test-Path $sshDir)) {',
      '    New-Item -ItemType Directory -Path $sshDir -Force',
      '    Write-Host "Created $sshDir"',
      '}',
      '',
      '# Add entry to config file',
      '$entry = @"',
      configEntry,
      '"@',
      '',
      '# Check if entry already exists',
      'if (Test-Path $configFile) {',
      '    $existingContent = Get-Content $configFile -Raw',
      '    if ($existingContent -like "*' + hostAlias + '*") {',
      '        Write-Host "Entry already exists in config file"',
      '        exit 0',
      '    }',
      '}',
      '',
      'Add-Content -Path $configFile -Value "$entry"',
      'Write-Host "SSH config entry added successfully!"',
      'Write-Host "You can now connect using: ssh ' + hostAlias + '"'
    ]
    return lines.join('\n')
  }

  // Linux/macOS bash script - use array join to avoid issues
  const bashLines = [
    '#!/bin/bash',
    '# Script to add SSH config entry',
    '',
    'SSH_DIR="$HOME/.ssh"',
    'CONFIG_FILE="$SSH_DIR/config"',
    '',
    '# Create .ssh directory if it doesn\'t exist',
    'mkdir -p "$SSH_DIR"',
    'chmod 700 "$SSH_DIR"',
    '',
    '# Check if entry already exists',
    'if grep -q "Host ' + hostAlias + '" "$CONFIG_FILE" 2>/dev/null; then',
    '    echo "Entry already exists in config file"',
    '    exit 0',
    'fi',
    '',
    '# Add entry to config file',
    "cat >> \"$CONFIG_FILE\" << 'EOF'",
    '',
    configEntry,
    'EOF',
    '',
    'chmod 600 "$CONFIG_FILE"',
    'echo "SSH config entry added successfully!"',
    'echo "You can now connect using: ssh ' + hostAlias + '"'
  ]
  return bashLines.join('\n')
}

/**
 * Parse existing SSH config file content
 * @param {string} content - SSH config file content
 * @returns {Array} Array of parsed host entries
 */
export const parseSSHConfig = (content) => {
  const entries = []
  let currentEntry = null

  const lines = content.split('\n')
  
  for (const line of lines) {
    const trimmed = line.trim()
    
    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith('#')) continue
    
    // Match Host directive
    const hostMatch = trimmed.match(/^Host\s+(.+)$/i)
    if (hostMatch) {
      if (currentEntry) {
        entries.push(currentEntry)
      }
      currentEntry = {
        alias: hostMatch[1],
        hostname: '',
        port: 22,
        user: '',
        identityFile: ''
      }
      continue
    }
    
    // Match other directives
    if (currentEntry) {
      const match = trimmed.match(/^(\w+)\s+(.+)$/i)
      if (match) {
        const [, key, value] = match
        const keyLower = key.toLowerCase()
        
        if (keyLower === 'hostname') currentEntry.hostname = value
        else if (keyLower === 'port') currentEntry.port = parseInt(value, 10)
        else if (keyLower === 'user') currentEntry.user = value
        else if (keyLower === 'identityfile') currentEntry.identityFile = value
      }
    }
  }
  
  // Add last entry
  if (currentEntry) {
    entries.push(currentEntry)
  }
  
  return entries
}

/**
 * Download content as a file
 * @param {string} content - File content
 * @param {string} filename - Download filename
 */
export const downloadAsFile = (content, filename) => {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export default {
  generateSSHConfigEntry,
  generateSSHConfig,
  getSSHConfigPaths,
  getSSHConfigInstructions,
  generateSSHConfigScript,
  parseSSHConfig,
  downloadAsFile
}

